### ISSUE TITLE
Modul don't work

### ISSUE THREAD

**Issue by gep-sher** [Crissium/python-dsl#1]
Hi, how does the module work?
I stole the code: git clone ... ; cd...
Then: pip install dsl2html ; python3 setup.py build
And what else ?
My virtual environment "myenv", does not contain the executable "dsl2html"

.../myenv
├── bin
│   ├── Activate.ps1
│   ├── activate
│   ├── activate.csh
│   ├── activate.fish
│   ├── pip
│   ├── pip3
│   ├── pip3.12
│   ├── pyglossary
│   ├── python -> python3.12
│   ├── python3 -> python3.12
│   └── python3.12 -> /usr/local/opt/python@3.12/bin/python3.12
├── include
│   ├── python3.12
│   │   └── Python.h
│   └── site
│       └── python3.12
│           └── pygobject
│               └── pygobject-3.0
│                   └── pygobject.h
├── lib
│   └── python3.12
│       └── site-packages
│           ├── PyICU-2.13.1.dist-info
│           │   
│           ├── _distutils_hack
│           │   
│           ├── cairo
│           │   
│           ├── distutils-precedence.pth
│           ├── dsl.cpython-312-darwin.so
│           ├── dsl2html-0.1.5.dist-info
│           │   ├── INSTALLER
│           │   ├── LICENSE.txt
│           │   ├── METADATA
│           │   ├── RECORD
│           │   ├── REQUESTED
│           │   ├── WHEEL
│           │   └── top_level.txt
│           ├── gi
│           │ 
│           ├── icu
│           │   
│           ├── pip
│           │   
│           ├── pip-24.1.dist-info
│           │   
│           ├── pkg_resources
│           │   
│           ├── pycairo-1.26.0.dist-info
│           │   
│           ├── pyglossary-4.6.1.dist-info
│           │   
│           ├── pygobject-3.48.2.dist-info
│           │   
│           ├── pygtkcompat
│           │  
│           ├── setuptools
│           
├── pyvenv.cfg
└── share
    └── pyglossary
        ├── AUTHORS
        ├── about
        ├── config.json
        ├── help
        ├── license-dialog
        ├── license.txt
        ├── plugins-meta
        │   └── index.json
        └── res
            ├── author-22.png
            ├── dialog-information-22.png
            ├── license-22.png
            ├── pyglossary.ico
            ├── pyglossary.png
            ├── pyglossary.svg
            ├── resize-16.png
            ├── resize.png
            └── resources.xml

245 directories, 1819 files

What is the next step? Please

**Comment by Crissium** [comment]
This is a Python library that you import into your own project. All you need is the function `dsl.to_html()`, which converts the DSL text into HTML.

I don't provide an executable that converts DSL dictionaries into HTML. If that's what you need, please check out [pyglossary](https://github.com/ilius/pyglossary).

**Comment by gep-sher** [comment]
... Thanks for the reply'.
I use the command line from the folder "python-dsl", where the code was downloaded.
./python-dsl
├── LICENSE.txt
├── MANIFEST.in
├── README.md
├── build
│   ├── lib.macosx-13.0-x86_64-cpython-312
│   │   └── dsl.cpython-312-darwin.so
│   └── temp.macosx-13.0-x86_64-cpython-312
│       └── src
│           ├── build.o
│           ├── dslmodule.o
│           ├── parse.o
│           └── utils.o
├── pyproject.toml
├── setup.py
├── src
│   ├── build.cc
│   ├── dsl.h
│   ├── dslmodule.cc
│   ├── parse.cc
│   └── utils.cc
└── tree_python_dsl.txt
6 directories, 16 files

And how to start this function?
(myenv) xxx python-dsl %

**Comment by Crissium** [comment]
The function cannot be 'started.' It can only be called by your own Python code.

I don't know your use case. But if you intend to convert a DSL dictionary into HTML you'd need to scan the file and convert each definition you find.

**Comment by gep-sher** [comment]
... It's okay now.
Thanks for support 🤝
